import PartnerSignupScreen from "@/components/auth/PartnerSignupScreen";

// This page is intentionally NOT linked from anywhere in the public app.
// It is only reachable via a unique invite link generated by an M1 admin
// from Admin Dashboard > Databases > Partners Database > "Add a new partner".
// The [token] segment should be validated against the pending invite record
// before rendering the form (backend integration — TODO once API is ready).

export default async function PartnerSignupPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  await params;
  // TODO: validate token against backend before rendering the form.
  return <PartnerSignupScreen />;
}
